name = "fidbak-api"
main = "src/index.ts"
compatibility_date = "2024-09-01"

# D1 database binding (use a real database_id in production deploys)
[[d1_databases]]
binding = "DB"
database_name = "fidbakprod"
database_id = "745c56c8-1b28-4c55-a7b7-8333671687d3"
[observability]
enabled = true

# IMPORTANT:
# Do NOT set [vars] at the top-level. Leaving it empty ensures
# deployments from Wrangler will NOT overwrite Dashboard-managed vars in production.

# Explicit production environment (relies on Dashboard vars)
#[vars]

[env.production.vars] 
name = "fidbak-api"       # same as dashboard service
CLERK_ISSUER = "https://noble-bat-12.clerk.accounts.dev"
CLERK_JWKS_URL = "https://noble-bat-12.clerk.accounts.dev/.well-known/jwks.json"
# CLERK_AUDIENCE = "your-audience"      # optional
FIDBAK_STRICT_CORS = "1"                 # dev: permissive; set to "1" to test strict
FIDBAK_DASH_ORIGIN = "https://fidbak-dash.pages.dev" # dashboard dev origin
FIDBAK_DASHBOARD_BASE = "https://fidbak-dash.pages.dev"

[[env.production.d1_databases]]
binding = "DB"
database_name = "fidbakprod"
database_id = "745c56c8-1b28-4c55-a7b7-8333671687d3"

# Local environment for safe dev deploys that won't touch production
[env.local]
name = "fidbak-api-local" # separate worker name; deploy with: wrangler deploy --env local

# Local-only variables (placeholders). Fill these in locally if you need to test deploys.
[env.local.vars]
CLERK_ISSUER = "https://noble-bat-12.clerk.accounts.dev"
CLERK_JWKS_URL = "https://noble-bat-12.clerk.accounts.dev/.well-known/jwks.json"
# CLERK_AUDIENCE = "your-audience"      # optional
FIDBAK_STRICT_CORS = "0"                 # dev: permissive; set to "1" to test strict
FIDBAK_DASH_ORIGIN = "http://localhost:8080" # dashboard dev origin
FIDBAK_DASHBOARD_BASE = "http://localhost:8080"

# If you need a separate D1 for local, you can override bindings under [env.local]
# by adding another [[env.local.d1_databases]] block. Otherwise it will use the top-level binding.
[[env.local.d1_databases]]
binding = "DB"
database_name = "fidbakprod"
database_id = "745c56c8-1b28-4c55-a7b7-8333671687d3"